filebeat.modules:

filebeat.prospectors:

- input_type: log
  paths: ["/usr/local/log/*.log", "/usr/local/log/*/*.log"]
  ignore_older: "5m"

  multiline.pattern: '^[[:space:]]+|^Caused by:|^---[[:space:]]'
  multiline.negate: false
  multiline.match: after

output.logstash:
  hosts: ["logstash:5043"]

path.data: /data